# Generated by Django 5.1 on 2024-09-22 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['enrolled_at']},
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=uuid.UUID('40fdb71e-8c03-4ef0-8dc8-3c2fe30519cf'), on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='v1.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='v1.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('id', 'course')},
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='v1.lesson')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='v1.resource')),
            ],
            options={
                'db_table': 'lesson_resources',
                'unique_together': {('lesson', 'resource')},
            },
        ),
    ]
