import type { Metadata } from "next";
import { inter } from "@/app/fonts";
import '@/app/globals.css';
import Footer from "@/app/components/footer";
import { AuthProvider } from "./context/AuthContext";
import Header from "@/app/components/header";
import { CourseProvider } from "@/app/context/CourseContext";
export const metadata: Metadata = {
  title: "Unlock your knowledge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <CourseProvider>
            {children}
          </CourseProvider>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
